openwhyd/openwhyd

.codeclimate.yml
.travis.yml
README.md

Add a stub Travis integration (waiting for more tests)
Add a CodeClimate configuration with minimal quality analysis.
(Display some fancy badges on the README.) reverted for now.

CI / Code Quality tools integration

---

whydJS/app/controllers/LibUser.js

Leave protocol of user submitted website urls untouched

---

whydJS/public/js/settings.js

72/ user feedback deezer connect connection status

---

docs/whydJS-json-api.md
whydJS/test/api-client.js
whydJS/test/api/post.api.tests.js

This PR is not a fix. (the fix has to be made on the iOS codebase: https://github.com/openwhyd/openwhyd-ios/issues/3)
This PR contains:
- fixes for the documentation of the corresponding API endpoints
- automated tests for the corresponding API endpoints
- minor refactoring and re-indenting of automated tests

Issue #89: iPhone app cannot retrieve playlist tracks from API

---

whydJS/app/templates/feed.html
whydJS/public/css/common.css

Makes donation box clearer

---

whydJS/app/models/email.js

Updated email regex validation for new tlds

---

whydJS/package.json
whydJS/public/js/whydPlayer.js

demo video: https://www.youtube.com/watch?v=uHI8ghnrw3w

Workaround for issue #88: pause on lost focus + openwhyd-electron invite

---

whydJS/app/controllers/public/search.js

fix - checks

---

whydJS/app/controllers/consent.js
whydJS/app/controllers/userLibrary.js
whydJS/app/models/user.js
whydJS/config/app.route
whydJS/config/gdpr-consent-en.md
whydJS/config/gdpr-consent-fr.md
whydJS/test/.editorconfig
whydJS/test/specs/acceptance.tests.js

... before using openwhyd.
=> ✋ functional tests fail, as they need to be updated as well
next steps:

feat(gdpr-consent): ask user to consent to gdpr / privacy notice

---

whydJS/public/js/feed-trackorder.js

fix(profile): fix playlist re-ordering

---

.circleci/config.yml

Travis-ci is sometimes slow to start running tests. => Trying out Circleci as an alternative.

chore(ci): configure circleci

---

.circleci/config.yml
.github/workflows/nodejs.yml
.travis.yml
package-lock.json
package.json

Contibutes to #205. Follow up to #215.
Configure the GitHub Actions workflow so that it can replace our CircleCI workflow.
- split big step into smaller steps
- improve naming of workflow, job and steps
- run semantic-release
- add env vars (including secret gh token) for semantic-release
- The workflow should pass on this PR
- The version number from package.json should be bumped after merging this PR.

feat(ci): move semantic-release to github-actions workflow

---

app/controllers/uploadedFile.js

contribute #213
Error with no image path for senfFile function.
No overview changes
Spam search on tracks page

fix: render image with no path for sendFile (uploadFile.js)

---

package-lock.json
package.json
test/acceptance-cmds.js
test/specs/acceptance.tests.js
test/specs/bookmarklet.tests.js
test/specs/email-notifications.tests.js
test/web-ui.js
wdio.conf.js

On several machines (including on circle-ci, after upgrading node.js), I saw that webdriver-based tests were failing.
=> Upgrading from webdriver 4 to webdriver 5.

fix(deps): update webdriver.io (wdio)

---

app/models/mongodb.js
scripts/algolia-search-index/mongodb-wrapper.js

Closes #.
```
===
Sun, 27 Oct 2019 11:38:50 GMT, Warning (concise trace)
at Object.exports.init (/home/adrien/openwhyd/app/models/mongodb.js:163:23)
the options [useUnifiedTopology] is not supported
/home/adrien/openwhyd/node_modules/mongodb/lib/mongo_client.js:462
throw err
^
MongoError: Authentication failed.
at Function.MongoError.create (/home/adrien/openwhyd/node_modules/mongodb-core/lib/error.js:31:11)
at /home/adrien/openwhyd/node_modules/mongodb-core/lib/connection/pool.js:497:72
at authenticateStragglers (/home/adrien/openwhyd/node_modules/mongodb-core/lib/connection/pool.js:443:16)
at Connection.messageHandler (/home/adrien/openwhyd/node_modules/mongodb-core/lib/connection/pool.js:477:5)
at Socket.<anonymous> …
```

fix(db): fix db auth problem in production

---

test/api-client.js
test/api/auth.api.tests.js
test/api/post.api.tests.js
test/api/user.api.tests.js

Simplify tests by homogenizing the way JSON playloads are returned by API client.

fix(tests): homogenize returns of api client

---

.idea/.gitignore
.idea/inspectionProfiles/Project_Default.xml
.idea/misc.xml
.idea/modules.xml
.idea/openwhyd.iml
.idea/vcs.xml
app/controllers/private/register.js
package-lock.json
test/api/auth.api.tests.js
test/unit/argon2-tests.js

feat(security) use argon2 to hash user password
#246 
This PR does not yet solve the issue.
argon2-tests.js -> OK
auth.api.tests.js -> KO

feat(security): use argon2 to hash user password on sign up + tests

---

.github/workflows/nodejs.yml

It was using version 8. Let's use the same version as specified in `package.json` and `.nvmrc`
Also fixes indentation of `nodejs.yml`.

fix(ci): use node version 10 on github actions

---

app/templates/feed.html
app/templates/feed.js
app/templates/sideBox.html

Tidy up our home/feed template by extracting the "sidebox" (top-right box used for announcements) into a separate template.

fix(refact): extract "sidebox" announcements into dedicated template

---

public/js/bookmarklet.js

Contributes to #262.
The goal is to make the bookmarklet easier to read, understand and maintain.

fix(bookmarklet): [refactor] move browser-only code to end

---

app/templates/feed.html
app/templates/onboarding.html
app/templates/onboarding/bookmarklet-old.html
app/templates/onboarding/bookmarklet.html

fix(bookmarklet): fix and homogenize wording, second pass

---

app/templates/onboarding.html
public/css/onboarding.css

URL: `/pick/button` (alternative to `/button`, shown during onboarding process)
Before:
After:
Note: that page's content adapts to user's web browser

fix(bookmarklet): make "install" button more visible during onboarding

---

public/js/whyd.js

Closes #38 .
Display the dark logo on light background color.
I removed the browser cache hack javascript code found in the whyd.js file that will now allow css to take care of how the logo is displayed on the light navbar header or the homepage.
By inspecting the logo we can now see that css is taking care of when to display the correct dark or light logo based on classes found in the body tag

fix(ui): Hidden logo on search bug

---

.github/workflows/nodejs.yml

based on suggestions from https://github.com/jerray/publish-docker-action/issues/11#issuecomment-607077257
Follow up PR #306.

fix(release): attempt to publish tags on docker hub

---

docs/INSTALL.md

Precise url where to find data imported in install.md

docs: Precise url where to find data imported in install.md

---

docs/INSTALL.md

install instruction for docker with windows home : replace localhost with docker ip

docs: install instruction for docker with windows home

---

.eslintrc.json
package-lock.json
package.json

Adding settings for the linter to work with typescript files 
Install Typescript Linter / prettier Modules

fix: fixing the linter to work with typescripts files

---

.eslintrc.json

This problem on codacy (https://app.codacy.com/gh/openwhyd/openwhyd/pullRequest?prid=6070209):
- add a rule in ESLint's config, on top of Prettier's (https://stackoverflow.com/a/29312958/592254)

fix(lint): Expect single quotes

---

public/css/common.css

fix(css): Remove obsolete CSS definitions

---

app/controllers/admin/invites.js
app/controllers/collabPl.js
app/controllers/pgApp.js
app/controllers/pgGenre.js
app/controllers/recentActivity.js
app/controllers/userLibrary.js
app/models/analytics.js
app/models/searchMongo.js
app/models/track.js
app/models/user.js
app/templates/mainTemplate.js
scripts/start.sh

Cf [datadog log patterns](https://app.datadoghq.com/logs/patterns?from_ts=1596789163038&index=&live=true&stream_sort=desc&to_ts=1599381163038):

fix(logs): Reduce amount of logging in production

---

app/templates/userProfileV2.html
public/css/common.css
public/js/whyd.js

Closes #371 
Add playlist sort feature that includes an alphabetized option
added sort menu to the playlist header with a sort by date option and an alphabetized option
Use the profile side nav and click on the playlist menu item. On the playlist page you will now have a sort menu next to the playlist main header.
Let me know if there are any changes needed :smiley:

feat: Add sort playlist feature

---

app/templates/templateLoader.js

fix(379): Load templates synchronously, to prevent crash on CI

---

app/templates/feed.html
public/js/bookmarklet.js
public/js/bookmarkletLogic.ts

fix: Hotfixes

---

app/controllers/invite.js
app/controllers/pgApp.js
app/controllers/private/register.js
app/controllers/userLibrary.js
app/templates/feed.js
app/templates/invitePage.html
app/templates/invitePage.js
docs/API.md
public/css/userPlaylistV2.css

fix: Finish removal of "Playlist Contest"

---

app.js
app/models/activity.js
app/models/mongodb.js

Mostly based on observations of logs on Datadog.

fix: Various hotfixes

---

app/controllers/api/bandcampExtractor.js

fix: Check that the API is called from our own domain

---

app/controllers/api/contentExtractor.js
public/js/whydPlayer.js

Contributes to #132.
Cf https://github.com/openwhyd/openwhyd/issues/132#issuecomment-414131182.

feat(player): Enable background playback

---

app.js
app/controllers/consent.js
app/controllers/uploadedFile.js
app/lib/my-http-wrapper/http/Application.js
app/snip.js
app/templates/error.js
app/templates/mainTemplate.js

Synchronous IO calls are bad on a web server, because they block the processing of other requests.

fix(perf): Reduce use of synchronous IO calls

---

.dockerignore
.github/workflows/nodejs.yml
.gitignore
app/lib/my-http-wrapper/http/Application.js
cypress/plugins/index.ts
cypress/support/index.ts
docker-compose.yml
package-lock.json
package.json

Goals:
- being able to follow our progress in de-legacy-fying this project, on https://app.codacy.com/gh/openwhyd/openwhyd/dashboard
- identify parts of the code are not (yet) covered by tests

fix(tests): Track test coverage data using nyc

---

app/models/user.js
app/templates/settings.html
public/js/facebook.js
public/js/postBox.js
public/js/postBoxV2.js
public/js/settings.js
public/js/whyd.js
public/js/whydPlayer.js

Intent: clean and simplify the source code.

feat(facebook): Remove calls to Facebook Opengraph

---

app/templates/mainTemplate.js

Refs:
- https://www.datadoghq.com/blog/error-tracking/
- https://docs.datadoghq.com/fr/real_user_monitoring/error_tracking/?tab=siteamricaindedatadog#prise-en-main
- https://app.datadoghq.com/rum/

fix(debug): Track front-end errors with Datadog RUM

---

app/controllers/LibUser.js
app/controllers/userLibrary.js
cypress/fixtures/users.js
cypress/integration/acceptance.spec.ts
test/api/data.api.tests.js
test/api/post.api.tests.js
test/api/user.api.tests.js
test/fixtures.js

Re-apply PR #418 with hotfix.
Problem: error when trying to open https://openwhyd.org/adrien/playlist:
- error while calling "_id.getTimestamp()", at `  var when = post._id ? post._id.getTimestamp().getTime() : undefined;` (`app/templates/posts.js`)

fix(api): [retry] Regression on Data Export API + side effects between API tests

---

app/controllers/admin/tests/playlist.js
app/models/mongodb.js
cypress/integration/visual-snapshots.ts
public/css/common.css

Closes #410.
```sh
docker-compose up -d
node scripts/import-from-prod.js adrien
open http://localhost:8080/adrien
```
See:
- https://github.com/openwhyd/openwhyd/pull/421/checks?check_run_id=1584513814#step:12:265
- https://eyes.applitools.com/app/test-results/00000251793834889761/?accountId=zf2VcF6gtk2wqY43MNPslw~~

fix(UI): Broken Profile UI when not logged in

---

.github/workflows/ci.yml
applitools.config.js
test-email.sh

Goal: fix failed CI check from Applitools after merging each PR.
Source: https://applitools.com/docs/topics/integrations/github-integration-ci-setup.html

fix(ci): Add APPLITOOLS_BATCH_ID env var

---

package-lock.json
package.json

Changelog: https://docs.cypress.io/guides/references/changelog.html#6-3-0

fix(deps): Cypress 6.3.0

---

app/models/follow.js
app/models/track.js
test/api/follow.api.tests.js

fix(api): Follow API returns 404

---

app.js

Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies

fix(security): Enable secure and sameSite for session cookies

---

.dockerignore
.github/workflows/ci.yml
Dockerfile
app.js
app/lib/my-http-wrapper/http/Application.js
app/models/analytics.js
docker-compose.yml

Reference: [Node.js Docker Cheatsheet · OWASP](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/NodeJS_Docker_Cheat_Sheet.md)

fix(docker): Apply OWASP recommendations

---

test/api-client.js

To ease the writing and troubleshooting of automated tests.

fix(tests): make loginAs() report an error if cookie was not set

---

app/models/logging.js
test/api/security.api.tests.js

Improves #496, as suggested on this report: https://huntr.dev/bounties/6b8acb0c-8b5d-461e-9b46-b1bfb5a8ccdf/

fix(security): Prevent redirect to a disguised domain

---

.github/workflows/ci.yml
cypress/plugins/index.ts

Cf https://github.com/openwhyd/openwhyd/pull/501#pullrequestreview-829042741

fix(tests): Re-enable coverage tracking from Cypress

---

app/templates/mainTemplate.js

cf https://huntr.dev/bounties/c9061d03-f0e5-4eff-aa0b-7364b48de647/

fix(security): XSS with user name on profile

---

.github/workflows/ci.yml

cf duration of `use npm cache` in https://github.com/openwhyd/openwhyd/runs/4570216410?check_suite_focus=true: 2m20 !

ci: Make npm cache faster

---

.github/workflows/ci.yml
package.json
public/js/bookmarklet.js
public/js/bookmarkletUI.ts

... to detect if changes were made in bookmarklet.js (result of build) instead of on its source TypeScript files.

fix(ci): Make sure that bookmarklet.js build is up to date

---

app/emails/notifComment.html
app/emails/notifCommentReply.html
app/emails/notifMention.html
app/models/applenotif.js
app/templates/invitePage.js
public/css/postBoxV2.css
public/css/userPlaylistV2.css
public/investors/style.css
public/js/DeezerExport.js
public/js/bookmarklet.js
public/js/bookmarkletLogic.ts
public/js/hotTracks.js
public/js/whyd.js
public/js/whydEmbed.js
public/js/whydRemotePlayer.js

From https://sonarcloud.io/project/issues?id=openwhyd_openwhyd&open=AX3JUsBHAKdy36cCFTIT&resolved=false&severities=BLOCKER.

fix: Fix most "blocker" issues reported by SonarCloud

---

app/snip.js
app/templates/logging.js
app/templates/redirectPage.html
test/api/security.api.tests.js

Follow up for PR https://github.com/openwhyd/openwhyd/pull/519.
Source: https://huntr.dev/bounties/d66f90d6-1b5f-440d-8be6-cdffc9d4587e/

fix(security): Reject url-encoded script element appended to redirect URL

---

app/models/post.js
test/__snapshots__/approval-hot-tracks.jest.test.js.snap
test/approval-hot-tracks.jest.test.js

Bug fix from https://github.com/openwhyd/openwhyd/pull/529.

fix(hot-tracks): Increment score when track is reposted

---

test/__snapshots__/approval-hot-tracks.jest.test.js.snap
test/approval-hot-tracks.jest.test.js

To cover pagination and data-merging logic.

test(hot-tracks): Add more approval tests for hot tracks

---

public/js/facebook.js

fix(facebook): Facebook login fails silently

---

app/controllers/api/post.js
test/api-client.js
test/integration/data.api.tests.js
test/integration/post.api.tests.js

See https://github.com/openwhyd/openwhyd/pull/546#issuecomment-1120230250 for investigation notes.

fix: Post can be updated just by its owner

---

app/models/user.js

Fixes #561.
Necessary for integration of approval tests in https://github.com/openwhyd/openwhyd/issues/559 / https://github.com/openwhyd/openwhyd/pull/560.

fix: New playlist number must be the highest

---

app/controllers/api/playlist.js

Fixes a regression from https://github.com/openwhyd/openwhyd/pull/563.

fix: Regression on playlist sharing API

---

.github/workflows/ci.yml

cf https://github.com/openwhyd/openwhyd/actions/runs/3786810189/jobs/6438042452#step:8:6724

ci: try to fix occasional `APPLITOOLS_API_KEY env variable is missing`

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

Objective: fix most warnings from GitHub Actions CI:
source: https://github.com/openwhyd/openwhyd/actions/runs/3786940087

ci: update github actions

---

package-lock.json
package.json

may replace https://github.com/openwhyd/openwhyd/pull/584

fix(deps): Upgrade approvals

---

app/models/mongodb-shell-runner.js
app/models/mongodb.js
config/initdb.js

Startup warnings:
- `[MONGODB DRIVER] Warning: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.`
- `[MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`
- `DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`
Cf https://github.com/openwhyd/openwhyd/actions/runs/5645897621/job/15292661458#step:7:10
Look for the presence or absence of these warnings in the "Logs from docker-compose" step of the "Docker" CI job.

fix: 3 mongodb warnings at app startup

---

app/controllers/api/post.js
app/controllers/private/search.js
app/models/activity.js
app/models/follow.js
app/models/mongodb-shell-runner.js
app/models/mongodb.js
app/models/notif.js
app/models/user.js
scripts/import-from-prod.js

fix: throw on invalid MongoId

---

app/models/follow.js
app/models/mongodb.js
app/models/post.js
app/models/user.js

cf https://app.datadoghq.com/logs?query=-status%3Ainfo&cols=host%2Cservice&event=AgAAAYmiu5tg3CccygAAAAAAAAAYAAAAAEFZbWl1NmY4QUFDRExBN2VBZUxrMGdBQQAAACQAAAAAMDE4OWEzMzgtYmY5ZS00Y2I4LTg5NWEtY2RmNjM0NDc4ZmVl&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1690652100000&to_ts=1690652400000&live=false

fix: `Cannot convert undefined or null to object`

---

.github/workflows/ci.yml

Cf
https://github.com/goldbergyoni/nodebestpractices#-519-install-your-pac kages-with-npm-ci
Closes #.

ci: use npm ci instead of npm install

---

app/models/mongodb.js
app/models/post.js
test/approval-tests-helpers.js

fix(mongodb): let `ObjectId` constructor throw on invalid values

---

app/controllers/api/post.js
app/controllers/private/upload.js
app/lib/my-http-wrapper/http/Application.js
app/models/user.js

Examples of errors we don't want to see on Datadog logs:

fix(logs): don't log reported errors

---

app/controllers/admin/users.js
app/controllers/api/follow.js
app/controllers/api/unsubscribe.js
app/controllers/consent.js
app/controllers/uploadedFile.js
app/models/comment.js
app/models/email.js
app/models/emailSendgrid.js
app/models/facebook.js
app/models/logging.js
app/models/mongodb.js
app/models/post.js
app/models/searchAlgolia.js
app/models/searchElastic.js
app/models/solrIndex.js
app/models/user.js

contributes to #638.
goal: make unhandled errors stand out (compared to usual logs), and easier to troubleshoot, in datadog.

fix(logs): log errors thru `stderr`, with stack trace

---

app/models/mongodb.js

Follow up of PRs #676 and #666.
Contributes to #634.

fix: `Callbacks are deprecated` eslint warnings in mongodb model

---

app/models/notif.js

Follow up of PRs #677, #676 and #666.
Contributes to #634.

fix: eslint warnings in `notif` model

---

app/models/track.js

Follow up of PRs #678, #677, #676 and #666.
Contributes to #634.

fix: deprecated mongodb calls in `track` model

---

app/controllers/testing/refresh.js
app/controllers/testing/reset.js
app/nodejs-type-extensions.d.ts
test/3rd-party/algoliasearch.test.js
test/api/legacy.post.api.tests.js
test/api/playlist.api.tests.js
test/approval-tests-helpers.js
test/fixtures.js
test/unit/snip-tests.js

fix(tests): improve helpers to prevent doubts experienced in PR #680

---

test/api/legacy.post.api.tests.js
test/approval-tests-helpers.js
test/approval/hot-tracks/hot-tracks.approval.test.js
test/approval/posting/posting.approval.tests.js
test/approval/routes/routes.approval.tests.js
test/fixtures.js

Contribues to #684.
Next steps:
- stop using fixtures.cleanup()
- make sure that db state is reset everywhere it needs to be

fix(tests): use `OpenwhydTestEnv` class instead of `startOpenwhydServer()`

---

app/models/mongodb.js
config/initdb.js
scripts/algolia-search-index/algolia-utils.js
scripts/algolia-search-index/mongodb-wrapper.js
scripts/algolia-search-index/run-diff-reindex.js

Follow up of PR #826.
References:
- https://www.algolia.com/doc/api-reference/api-methods/browse/#examples

fix(start-up): remove old db migrations + count documents per collection
