openwhyd/openwhyd

- whydJS/app/emails/welcome.html
- whydJS/app/templates/feed.html
- whydJS/app/templates/hotTracks.html
- whydJS/public/about/index.html
- whydJS/public/html/landingOpen.html
- whydJS/public/html/landingPageLaunch.html
- whydJS/public/press/index.html
Replace blog links / mentions with GitHub ones.
- in email templates
- in web templates
- in the "About" redirection page
> Replace blog references with github references

- whydJS/app/templates/mainTemplate.js
PR for issue #29 . Adds metadata to main html, twitter relies on existing og:* meta tags for rest of info so no need to duplicate there.
Also for the 'site' property I used @open_whyd. They define it as:
> twitter:site
The Twitter @username the card should be attributed to. Required for Twitter Card analytics .
Let me know if that works.
> Added twitter card metadata to main template js

- docs/whydJS-json-api.md
This PR adds a table of content on the json API docs.
This helps get an overview of what's available in the json API.
Right now the TOC can only link to sections, because endpoint do not have proper titles.
I might work on PR to improve that in the future.
> Adds TOC to json API docs

- app/controllers/invite.js
- app/models/notifEmails.js
- app/templates/feed.html
Contributes to #178.
The email invite system has been abused between October 10th and 11th, causing our SendGrid account to go over-quota, which caused the email reset procedure emails (see #178) and others to not be sent after that incident.
RIP
> fix(security): disable email invites

- app/controllers/api/post.js
Contributes to #179.
Will log `warning: skipping invalid pId value in incrPlayCounter` + the value of `pId` whenever it's not a valid ObjectId.
> diagnostic: log invalid value of pId from incrPlayCounter()

- app/controllers/api/unsubscribe.js
- app/models/user.js
- test/acceptance-cmds.js
- test/specs/email-notifications.tests.js
- test/web-ui.js
Closes #186.
- fixes reduction of frequency for email notifications
- fixes message after unsubscribing from notification emails
- refactors unsubscribe logic, for better clarity
- adds tests for email notifications
- adds `browser.clickOnVisibleSelector()` wdio command
- adds `webUI.signup()` for tests
> fix(email-notif): ability to unsubscribe from notification emails (#186)

- app.js
Bug: a user reported that the "unsubscribe" link from his digest/notification email did not work:
Source: https://github.com/openwhyd/openwhyd/commit/cc3af51b2d24e98d24e10583add56ab83bd535de#commitcomment-33865126
This PR fixes the way the URL_PREFIX is computed when running in production. It should fix the URL of unsubscribe links.
> fix: append PORT to URL_PREFIX only if WHYD_URL_PREFIX is not provided

- app.js
Closes #208.
User needs to login again, everytime they restarts their browser. (including Openwhyd's iOS and Electron apps)
Specify a `maxAge` for cookies, so that they don't become browser-session-based by default.
1. open an openwhyd session by logging in
2. shut down your web browser, then restart it
3. you should still be connected to your openwhyd account
> fix(sessions): make user cookie persistant

- app.js
Closes #208.
In #209, I re-introduced cookie expiration using `express-session`'s `maxAge` property, but had defined it at the wrong path of the settings object.
Now defined in `cookie.maxAge` instead of just `maxAge`.
See #209.
> fix(sessions): define maxAge in the cookie property

- config/gdpr-consent-en.md
This PR replaces "RGPD" by "GDPR", on the English version of the GDPR consent page:
> fix: typo on gdpr consent screen

- .github/workflows/nodejs.yml
Use GitHub Actions to run automated tests whenever a pull request targets `master`, or a commit is merged to `master`.
Alternative if our current and previous CI systems: CircleCI and TravisCI.
This reference helped a lot: [Workflow syntax for GitHub Actions - GitHub Help](https://help.github.com/en/articles/workflow-syntax-for-github-actions)
Related: #205.
Next step, if it works well:
> create a mongodb job based on docker image

- .eslintrc.json
To prevent ESLint errors on keywords like `const` and `await`.
> fix(eslint): support ES6 and ES2017 syntax

- app/models/mongodb.js
- package-lock.json
- package.json
- scripts/algolia-search-index/mongodb-wrapper.js
Initial goal was to fix the following warning: `DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect`
As a first step, this PR fixes the `db.collections is not a function` error, when trying to run `docker-compose up --build`.
- upgrade the `mongodb` client to a more recent version: `2.2.33`
- switch to the new Mongo URI format
```
$ docker-compose up --build -d
$ npm run test-docker
```
> fix(mongodb): prevent "db.collections is not a function" error

- .eslintrc.json
- docs/INSTALL.md
- scripts/import-from-prod.js
Closes #220.
When developing and/or testing features (e.g. the "load more" button, see #221) in a local environment, it can be handy to have some posts in the local database.
Introduce `./scripts/import-from-prod.js` which loads [adrien's profile and posts](https://openwhyd.org/adrien) to the local/testing database.
Run this after starting a local database server (e.g. with `$ docker-compose up`):
```sh
$ node scripts/import-from-prod.js
```
=> http://localhost:8080/all should display several pages of tracks imported from https://openwhyd.org/adrien.
> feat(dev): script to import a user's posts from production, for #220

- app/controllers/api/login.js
- app/models/emailSendgrid.js
- app/models/logging.js
- app/models/user.js
- app/snip.js
- docs/INSTALL.md
A user kindly reported that in order to better protect privacy of user-identifiable data in case of data leak, we should prevent the logging of email addresses and md5 hashes.
- update `request.logToConsole()` to scramble/anonymise values of `email` and `md5` fields
- call the same method in appropriate places where user data is logged
- remove a useless log that contains user data
1. run the server locally with `docker-compose up`
2. open http://localhost:8080/login in a browser
3. type an email address and password (even fake)
4. the value of your email address and md5 should not be disclosed in the stdout logs of `docker-compose up`:
```
=== Sun, …
```
> fix(privacy): don't log email addresses and password hashes

- app/templates/mainTemplate.js
- app/templates/postEditV2.html
- public/html/YoutubePlayerIframe.html
- public/html/YoutubePlayerIframeLocal.html
- public/js/ContentEmbed.js
- public/js/bookmarklet.js
- public/js/whydEmbed.js
- test/old/snip.tests.js
Closes #262.
Since Google disabled our historic YouTube API Key, on February 20th, users have not been able to add YouTube tracks to their Openwhyd profile.
Create dedicated YouTube API Keys for each component.
```sh
$ git pull
$ docker-compose up --build --detach
$ nvm use
$ npm install
$ npm run docker:test
```
> fix(#262): user can add YouTube tracks (when new keys are active)

- app/templates/mainTemplate.js
- app/templates/postEditV2.html
- public/html/YoutubePlayerIframe.html
- public/html/YoutubePlayerIframeLocal.html
- public/js/ContentEmbed.js
- public/js/bookmarklet.js
- public/js/whydEmbed.js
- test/old/snip.tests.js
Closes #262.
Since Google disabled our historic YouTube API Key, on February 20th, users have not been able to add YouTube tracks to their Openwhyd profile. PR #263 did not seem to help. Probably because quotas were broken.
- Create a new Google Project to hold new YouTube API Keys.
- Create dedicated YouTube API Keys for each component.
```sh
$ git pull
$ docker-compose up --build --detach
$ nvm use
$ npm install
$ npm run docker:test
```
> fix(#262): user can add tracks thanks to new google api project for youtube

- public/js/bookmarklet.js
The bookmarklet (i.e. Chrome Extension) is the what consumes the most quota.
As it makes our new Google Project over-quota, I'm opening a new one just for this.
See https://github.com/openwhyd/openwhyd/issues/262#issuecomment-592952454
> fix(#262): specify dedicated YouTube API key for bookmarklet

- app/templates/postEditV2.html
The track edition/add dialog (i.e. `postEditV2.html`) is the second biggest consumer of our YouTube API usage quota.
As it makes our new Google Developer Project over-quota, I'm opening a new one just for this: `openwhyd-1`.
See https://github.com/openwhyd/openwhyd/issues/262.
> fix(#262): specify dedicated YouTube API key for postEditV2

- app/templates/mainTemplate.js
The YouTube API quota of our main Google Developer Project was reached pretty quickly, causing Openwhyd failing to add tracks from YouTube, and automated E2E tests to fail. (See #262)
I've opened a new Google Developer Project just for the key used in `mainTemplate`: `openwhyd-4`.
> fix(#262): specify dedicated YouTube API key for mainTemplate

- app/templates/postEditV2.html
Closes #269.
Fixes a regression introduced in https://github.com/openwhyd/openwhyd/pull/263/files#diff-d04a3fa73a7dd2a179772cc75555275eR109: a Hogan/Mustache template became invalid after prettier processed it on save.
> fix(#269): invalid template caused crash when adding from bookmarklet

- app/templates/sideBox.html
> feat(sideBox): inform about YouTube issues

- .github/workflows/nodejs.yml
To fix failing CI workflow: https://github.com/openwhyd/openwhyd/runs/477958067
Initially, I thought that some dependencies were missing.
Actually, downgrading the `ubuntu` images fixed the issue.
Possible next step: simplify `nodejs.yml` by using `cypress-io/github-action@v1` instead of setting up everything ourselves, as explained in https://github.com/cypress-io/github-action#basic.
> fix(ci): execution of Cypress test on GitHub Actions workflow

- public/js/bookmarklet.js
- test/specs/bookmarklet.tests.js
Contributes to #262.
The bookmarklet has been consuming more than 10000 YouTube API Calls per day, which is more than our allowed quota, for now.
Alternate between 2 keys, to double our capacity.
`$ npm run docker:seed && node_modules/.bin/wdio wdio.conf.js`
> fix(#262): extend youtube api quota from bookmarklet

- public/js/bookmarklet.js
Contributes to #262, to save YouTube API quota.
> fix(#262): bookmarklet to not fetch youtube metadata

- public/js/bookmarklet.js
- test/unit/bookmarklet-tests.js
Contributes to #262.
As mention in #262 following the reduction of our YouTube API quota, we need to make several changes to the bookmarklet in order to save some quota while keeping a good user experience. E.g. track titles should be extracted from the page instead of queried from YouTube API.
As these changes are quite structural and may introduce bugs in the bookmarklet, and as we don't have time to test it manually after each change, it's time to refactor the code in order to make that code testable by automated unit tests.
This PR is the first step of that refactor: it makes the bookmarklet loadable from Node.js.
See the diff, and disable the display of whitespace changes.
- export `detectTracks({ window, ui, urlDetectors })`, `makeFileDetector()` and `makeStreamDetector(players)`
- …
> refactor: add unit tests for bookmarklet

- public/js/bookmarklet.js
- test/unit/bookmarklet-tests.js
Contributes to #262. Follow up of #280.
As mentioned in #262 following the reduction of our YouTube API quota, we need to make several changes to the bookmarklet in order to save some quota while keeping a good user experience. E.g. track titles should be extracted from the page instead of queried from YouTube API.
As these changes are quite structural and may introduce bugs in the bookmarklet, and as we don't have time to test it manually after each change, it's time to refactor the code in order to make that code testable by automated unit tests.
This PR is the second step of that refactor: it enables adaptive metadata enrichment for the page itself (e.g. youtube track page), while preventing duplicates in the results.
See the diff, and disable the display of whitespace changes.
- add …
> fix(bookmarklet): refactor bookmarklet and add tests for #262

- public/js/bookmarklet.js
- test/unit/bookmarklet-tests.js
Contributes to #262. Follow up of #281 and #282.
After YouTube reduced our API quota, we resorted to specifying "(YouTube track)" as the title of tracked extracted from YouTube pages using the bookmarklet, in order to save some quota.
This PR intends to determine the actual name of the track by extracting text from the DOM, and therefore to get rid of those "(YouTube track)" titles on newly added tracks.
- completely get rid of forced "(YouTube track)" titles 🥳
- add feat: "return a track with metadata from a YouTube page that lists that track as a link"
- add feat: "return a track with the expected name when that track was found as a link from a YouTube page" (i.e. remove noise from title)
- add feat: "return the page's track with metadata from a YouTube page when the same track is also …
> feat(bookmarklet): extract youtube track names from page

- app.js
- config/initdb_testing.js
- cypress/fixtures/users.js
- cypress/integration/acceptance.spec.ts
- cypress/integration/bookmarklet.spec.ts
- cypress/integration/stream.spec.ts
- cypress/support/commands.js
- cypress/support/index.d.ts
- docs/INSTALL.md
- test/reset-test-db.js
In PR #296, we found out that a reformat of our front-end js files including mustache/hogan blocks caused runtime errors which prevented the "load more" button to work as expected.
In order to prevent future regressions on pagination and runtime errors, this PR adds Cypress tests.
Note: It's expected that the Cypress tests fails, until we merge #296.
> test(#295): add non-regression test for pagination

- app.js
It turns out that the `conciseTrace` function actually pollutes stack traces more than anything, during development/debugging => let's get rid of it.
> feat(logs): Simplify logging to stdout and stderr

- .dockerignore
Contributes to #309. 
Log files were found while checking the contents of our Docker image, in PR #306. => Let's ignore them.
> fix(docker): ignore log files

- app/controllers/discover.js
Closes #21 
Prevent redirect error and allow page to load for guest users
I removed some conditions redirecting the user from 
https://openwhyd.org/discover/ranking to https://openwhyd.org/discover/featured.
Since this redirect was causing the page to throw an error instead of actually loading the redirected page I would think it is best to just load the rankings page. Then the user can click on the featured tab to go the the featured page.
The page is now loading when a guest user goes to https://openwhyd.org/discover/ranking
> fix(ui): redirect error when landing on rankings page

- .github/workflows/docker.yml
Closes #333 .
Forcing cypress version 3.8.3 on the Docker Workflow with npx
> fix(CI): Force cypress v3.8.3 on the Docker Workflow

- .github/semantic.yml
Forcing the CI to only check the PR title instead of checking all of the commits in the PR
> fix: Only checking the PR title

- .eslintrc.json
Second tentative, after #340.
Reference: https://github.com/adrienjoly/vscode-nodejs-typescript-eslint-prettier-ava-boilerplate/blob/master/.eslintrc.js
> fix(int): Codacy still thinks we want double quotes

- .eslintrc.json
- tsconfig.json
Fixes the following "Problem" listed by Visual Studio code, when opening a JS file:
> Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: test/unit/notif-tests.js.
> The file must be included in at least one of the projects provided.
> fix(linter): Re-enable linting of JS files in VSCode

- app/templates/feed.html
The "what's new" link does not work anymore. Rather than fixing something that does not seem to be useful, let's remove it.
> fix: Remove Barelog / Productfeed

- app/templates/feed.html
Contributes to #397.
A `polling new tracks...` logs appearing repeatedly after visiting the full stream (`/all`), even after navigating. Causing a lot of requests to our API.
Remove the auto-refresh of the "full stream".
> fix(ui): Never-ending refresh of full stream

- public/js/bookmarkletUI.ts
PlayemJS has been maintained for Openwhyd, to play and detect tracks, by communicating with the APIs of the streaming sources we support.
While PlayemJS has supported more sources than most alternative players we have found online, its codebase has become hard to maintain, so it suffers from a lack of updates, which lead to numerous problems taking a lot of time and effort to fix: e.g. #272, #262, #192, #190, #143, #132, #128, #16...
In order to simplify Openwhyd's codebase and make it easier for us to replace PlayemJS with an alternative, let's start by trying to remove it from the bookmarklet and see if anybody misses it from there.
> fix(bookmarklet): Remove PlayemJS from bookmarklet

- public/js/whyd.js
Closes #411 
Currently the sort playlist feature is using the index and paylistname data attributes to sort by date and alphabet. The issue is that I did not realize that the array sort function takes into consideration lower and upper case when sorting. 
Also the index is being sorted as a string rather than a number which causes the playlist to be in the incorrect order when sorting by date.
The sort function will now lower case all playlist titles and convert index strings into numbers before sorting to prevent these bugs.
If you currently sort the playlist with a user who has more than 10 playlists https://openwhyd.org/adrien/playlists the inspector shows an unexpected sort behavior.
After this update the sort by date will sort the playlist by the `data-index` attribute by ascending …
> fix: sort playlist feature bug

- package.json
- test/api/auth.api.tests.js
- test/api/post.api.tests.js
- test/api/user.api.tests.js
- test/fixtures.js
`user.api.tests.js` fails if it is not run after `auth.api.tests.js`, because the former relies on the presence of a user that was added to the db by the latter.
Proof, after resetting the db between tests: https://github.com/openwhyd/openwhyd/pull/417/checks?check_run_id=1581677648#step:10:114
Reset the db between each test suite, to prevent side effects.
> fix(tests): Clean up the database between each API test suite

- app/models/emailSendgrid.js
Cf [Upgrade your authentication method to API keys | SendGrid Documentation](https://sendgrid.com/docs/for-developers/sending-email/upgrade-your-authentication-method-to-api-keys/#upgrade-to-api-keys-for-your-smtp-integration)
> fix(email): Use API key for Sendgrid auth

- public/css/common.css
Closes #434 .
Adds a z-index to the `searchResults` div, to allow selecting of the previously blocked item.
I tested this in the browser, just adding a z-index of 1 in `common.css`
> fix(UI): allow selection of previously blocked items in search results div

- .github/workflows/ci.yml
- applitools.config.js
This reverts changes from PR #432, because the error happened again after merging to master.
I also disabled github integration from Applitools' admin.
> fix(ci): Revert Applitools configuration for GitHub integration

- cypress/integration/bookmarklet.spec.ts
- public/js/postBoxV2.js
Contributes to #439, at least for YouTube tracks.
The bug is probably caused by https://github.com/openwhyd/openwhyd/pull/429/files#diff-d0670720fd54d514c34d0215269319d1cc83b4fcca7113085edd1040a262febcR3.
> fix(bookmarklet): "Identifier 'globals' has already been declared" when adding a track

- app/controllers/api/bandcampExtractor.js
- test/unit/unit-tests.js
See https://github.com/openwhyd/openwhyd/pull/443/checks?check_run_id=1849601856#step:9:109:
```
1) bandcampExtractor
should extract the stream URL from an actual track page:
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
2 !== 1
+ expected - actual
-2
+1
at Context.<anonymous> (test/unit/bandcampExtractor-tests.js:35:12)
```
> fix(bandcamp): De-duplicate stream URLs from Bandcamp

- app/models/facebook.js
- app/models/mongodb-shell-runner.js
- app/models/mongodb.js
- app/templates/mainTemplate.js
- config/initdb_testing.js
- cypress/fixtures/users.js
- public/html/testFbInvite.html
- public/js/facebook.js
Addresses:
- "Your Facebook SDK is out-of-date. Please upgrade to v5.0 for access to new privacy features." banner from https://developers.facebook.com/apps/169250156435902/dashboard/
- "App Inactive for More Than 90 Days" banner from https://developers.facebook.com/apps/118010211606360/dashboard/ and https://developers.facebook.com/apps/1059973490696893/dashboard/ (old *development* fb apps)
May also contribute to #370.
Refs:
- [Working with Facebook login from localhost - Stack Overflow](https://stackoverflow.com/questions/39800216/working-with-facebook-login-from-localhost/57607570#57607570)
- [Using the Graph API](https://developers.facebook.com/docs/graph-api/using-graph-api/)
- [Graph API - Web SDKs](https://developers.facebook.com/docs/javascript/reference/FB.api)
- [Facebook Login …
> fix(fb): Update Facebook login SDK

- cypress/integration/acceptance.spec.ts
E2e test "`Openwhyd should allow users to search external tracks`" [fails on CI](https://github.com/openwhyd/openwhyd/pull/468/checks?check_run_id=3371392720#step:7:130):
```
1) Openwhyd
should allow users to search external tracks:
AssertionError: Timed out retrying after 4000ms: Expected to find element: `a[onclick="window.goToPage('/sc/harissaquartet/no-service');return false;"]`, but never found it.
at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/acceptance.spec.ts:250:14)
```
Could be caused by recent Soundcloud API change. (see #465)
- Temporary fix: disable this test
- To prevent regressions on lookup of external track until we fix that test: add a test to lookup MP3 file.
> fix(tests): lookup external tracks

- test/api-client.js
In order to write approval tests on the features covered by `userLibrary.js`, it would be nice if the `api-client` helper provided a method to fetch HTML pages too.
- extract `getRaw()`, to allow fetching HTML pages
- make `get()` use `getRaw()`
- fix, while we're at it: in case of JSON parsing error, pass that error to the callback instead of printing it to console and returning the unparsed body
> fix(tests): extract getRaw(), to allow fetching HTML pages

- public/js/jquery-migrate-1.2.1.js
cf https://github.com/openwhyd/openwhyd/runs/4486269717?check_suite_focus=true#step:8:743
> fix(tests): Try to reduce Cypress flakiness by tracing JSON parsing errors

- public/js/facebook.js
- public/js/whydtr.js
Cf: https://github.com/openwhyd/openwhyd/runs/4486211855?check_suite_focus=true#step:8:4554
Hypothesis:
> The only events you can subscribe to now via the JS SDK are related to the auth status changing, and when social plugins embedded into a page have been rendered.
Source: https://stackoverflow.com/a/52051424/592254
> fix(tests): Try to reduce Cypress flakiness by removing FB tracking

- cypress.json
Looks like it's a known bug: https://github.com/cypress-io/cypress/issues/18502 or https://github.com/cypress-io/cypress/issues/14972
> fix(tests): Enforce Cypress timeouts despite retries

- cypress.json
cf https://github.com/openwhyd/openwhyd/pull/510, https://github.com/cypress-io/cypress/issues/18502 and https://github.com/cypress-io/cypress/issues/14972
> ci: Disable Cypress retries until it's fixed

- .github/workflows/ci.yml
- cypress.json
- cypress/support/commands.ts
- cypress/support/index.ts
- public/css/common.css
- public/js/whyd.js
Despite several attempts to improve the situation (see PRs #501, #504, #505, #507, #508, #510, #513, #520, #521, #522), Cypress tests are still flaky: they timeout for random reasons.
This timeout could be caused by the fact that:
- some XHR requests (e.g. to `/api/notif` to fetch notifications, and Deezer) may never respond => `onLoad` is never triggered
- when a new test starts, we call `/testing/reset` to refresh the DB, which can cause pending DB queries from never resolving
See https://github.com/openwhyd/openwhyd/pull/520#issuecomment-997704287.
- wait for Openwhyd server to be up and reset before running tests
- intercept and mock flaky XHR requests
- fail faster when test steps are hanging for too long
- reduce the amount of resources to load: fonts
> fix(tests): Fix cypress flakiness on CI by slowing down test setup

- package-lock.json
- package.json
Goal: reduce risk of flakiness of Cypress/e2e tests caused by timeouts from code-coverage plugin:
```
"after all" hook: collectBackendCoverage for "user unsubscribes from email notification":
CypressError: `cy.request()` timed out waiting `5000ms` for a response from your server.
```
cf https://github.com/openwhyd/openwhyd/runs/4638088166?check_suite_focus=true#step:8:1094
Upgrade `@cypress/code-coverage` and `istanbul-lib-coverage`, as suggested in https://github.com/cypress-io/code-coverage/issues/216#issuecomment-974791778.
> ci: Reduce risk of timeout from Cypress code-coverage plugin

- app/controllers/LibUser.js
- docs/API.md
- test/integration/data.api.tests.js
To support the development of an external/static web clients (e.g. https://glitch.com/edit/#!/openwhyd-mobile-client?path=TrackFinder.js%3A294%3A0).
> feat(api): Enable JSONP API for list of playlists

- wallaby.conf.js
Second tentative of https://github.com/openwhyd/openwhyd/pull/557, with unit and functional tests. (for now)
Done during [SHODAY 2022-05-09](https://github.com/openwhyd/openwhyd/issues/559).
See resulting screenshots in VSCode: https://github.com/openwhyd/openwhyd/pull/565#issuecomment-1121185962.
1. Install Wallaby's extension on VS Code, cf [Wallaby.js Tutorials: VS Code tutorial](https://wallabyjs.com/docs/intro/get-started-vscode.html?port=56094#remote-containers)
2. Open openwhyd's local repository in VS Code
3. Activate the "Wallaby.js: Select Configuration" command, using VSCode's palette (Cmd-Shift-P), then select the `wallaby.conf.js` file
4. Run the tests by activating the "Wallaby.js: Start" command, thru VSCode's palette or Wallaby's palette (Cmd-Shift-=)
5. Open the "Output" …
> tests: Run unit and functional tests with Wallaby

- Dockerfile
cf https://github.com/tj/node-prune#installation
See https://hub.docker.com/r/openwhyd/openwhyd/tags for impact on size:
(screenshot is before this PR is merged)
> ci: reduce docker image size

- .github/workflows/ci.yml
Cf https://github.com/openwhyd/openwhyd/actions/runs/5587330707/jobs/10212532677#step:8:125:
```
You passed the --parallel flag, but we do not parallelize tests across different environments.
This machine is sending different environment parameters than the first machine that started this parallel run.
The existing run is: https://cloud.cypress.io/projects/8mw8bh/runs
In order to run in parallel mode each machine must send identical environment parameters such as:
- specs
- osName
- osVersion
- browserName
- browserVersion (major)
This machine sent the following parameters:
{
"osName": "linux",
"osVersion": "Ubuntu - ",
"browserName": "Chromium",
"browserVersion": "113.0.5672.0.... (Expected: 114)",
"specs": [
"cypress/e2e/acceptance.spec.ts",
"cypress/e2e/bookmarklet.spec.ts", …
```
> fix(cypress): prevent browserVersion mismatch

- .github/workflows/ci.yml
- app/models/searchAlgolia.js
- package.json
- test/3rd-party/algoliasearch.test.js
Fixes #612.
HTTP `502` errors when posting tracks and updating user data, caused by `getIndex(...).addObjects is not a function` errors from `searchAlgolia.js` wrapper.
Because `addObjects` is deprecated, cf: https://www.algolia.com/doc/deprecated/api-clients/javascript/v3/methods/add-objects/.
- reproduce problem in a 3rd-party test.
- run 3rd-party tests on CI.
- fix the problematic call to algoliasearch.
```
$ ALGOLIA_APP_ID="XXXXX" ALGOLIA_API_KEY="YYYYY" npx jest test/3rd-party/algoliasearch.test.js
```
> fix(algolia): prevent http 502 errors on indexing operations

- .github/workflows/ci.yml
- app/models/post.js
- app/models/searchAlgolia.js
- app/models/user.js
- docker-compose.yml
- test/3rd-party/algoliasearch.test.js
Fixes #612.
- Finish migration from `algoliasearch` v3 to v4 (cf https://github.com/openwhyd/openwhyd/issues/612#issuecomment-1646585205), by following [their migration guide](https://www.algolia.com/doc/api-client/getting-started/update/javascript/?client=javascript)
- Re-enables indexing to Algolia
- Also removes a unused feature: sending multiple/batched search queries
> fix(algolia): finish algoliasearch upgrade migration

- app/controllers/uploadedFile.js
fixes #179.
32-byte identifier passed to the `uCoverImg` route/controller failing to compute as `ObjectId` (because they're not):
> fix(api): cover image requires a filename, to prevent `invalid ObjectId` error logs

- app/models/mongodb-shell-runner.js
- config/initdb.js
- config/initdb_testing.js
Db init script can fail randomly, e.g. 
```
web_1    | [db] Applying db init script: ./config/initdb.js ...
web_1    | node:internal/process/promises:246
web_1    |           triggerUncaughtException(err, true /* fromPromise */);
web_1    |           ^
web_1    | 
web_1    | [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Cannot read properties of undefined (reading 'createIndex')".] {
web_1    |   code: 'ERR_UNHANDLED_REJECTION'
web_1    | }
```
cf https://github.com/openwhyd/openwhyd/actions/runs/5713134067/job/15477946339#step:7:11
Make the following commit work: [fix: simplify …
> fix: simplify db initialization script

- app/controllers/api/post.js
- app/models/comment.js
- test/approval-tests-helpers.js
- test/integration/post.api.tests.js
Occasional error in production: `Cannot read properties of null (reading 'error')`
cf https://app.datadoghq.com/logs?query=host%3Aopenwhyd-2gb%20service%3Aopenwhyd_pm2%20filename%3Aapp-error.log%20&cols=host%2Cservice&context_event=AYmtODT2AAAb8z_CnuWguwAA&event=AgAAAYmtOCpeZSiWGQAAAAAAAAAYAAAAAEFZbXRPRFQyQUFBYjh6X0NudVdndXdBQQAAACQAAAAAMDE4OWFkODQtMWQzZC00MzE4LTgwNmYtZGQzZGMyNjU3MDIw&index=%2A&messageDisplay=inline&saved-view-id=1990243&stream_sort=time%2Cdesc&to_event=AgAAAYmth11Ypxv4tgAAAAAAAAAYAAAAAEFZbXRoMlptQUFCaXJBNVU4QXVicVFBQQAAACQAAAAAMDE4OWFkODktM2FiYy00YjNkLTkyNzEtNTljZTI5YTU5ZmIz&viz=&from_ts=1690827986558&to_ts=1690833476952&live=false
- report error when trying to delete a comment that does not exist
- report error when trying to delete a comment associated to a post that …
> fix(api): report errors properly on post/comment APIs

- .github/workflows/ci.yml
- app/controllers/LibUser.js
- app/controllers/LibUserProfile.js
- app/controllers/userLibrary.js
- app/models/logging.js
- docker-compose.yml
- scripts/import-from-prod.js
- test/integration/user.api.tests.js
Fixes #649.
Openwhyd's server logs `Skip value must be non-negative` errors from MongoDB, when the `after` GET/query parameter is provided twice to a user profile endpoint.
Why:
- when a GET/query parameter is provided twice, it's converted into an array of values
- converting an array to `Number` results in `NaN`, which is seen by MongoDB as a negative number.
- validate the `after` parameter (and others) so that duplicated parameters result in an error message
- ensure that behavior using an automated test
- [bonus] also fix `error response from daemon: configured logging driver does not support reading` when trying to read logs from mongodb container, by enabling logs and using a `tmpfs` volume
- [bonus] also fixes a bug regarding the max number of posts to include in an embedded …
> fix(#649): validate http parameters on user library pages

- app/controllers/testing/reset.js
- cypress/e2e/upload.spec.ts
Adding e2e test related to the upload of playlist images, so we can prevent regressions while fixing some errors logged in datadog:
> test: upload playlist images

- app/controllers/uploadedFile.js
- test/api-client.js
- test/api/user.api.tests.js
Motivation: reduce number of errors reported to Datadog => instead, notify clients when images are not found.
cf https://app.datadoghq.com/logs?query=Error%20error%20-%22slow%20request%22%20-%22POST_NOT_FOUND%22%20-%22page%20404%22%20&agg_m=count&agg_t=count&cols=host%2Cservice&index=%2A&messageDisplay=inline&source=monitor_notif&stream_sort=desc&viz=stream&from_ts=1692101314785&to_ts=1692706114785&live=true
> fix(api): return 404 on missing images => stop logging errors

- test/api/playlist.api.tests.js
- test/api/post.api.tests.js
- test/approval-tests-helpers.js
Contributes to #684.
Several FIXME suggest that some integration tests that rely on DB state are not isolated and may fail when default test users are modified.
Reproduced: 
- See [fix test, to match with schema of posts](https://github.com/openwhyd/openwhyd/pull/680/commits/08c3b1de801e26d5cc176b299754201dc06b56d6), as seen in failing `post` API tests, only after they are run after `playlist` API tests (which mutate DUMMY_USER in the db). See logs: https://github.com/openwhyd/openwhyd/actions/runs/5998120167/job/16265796818?pr=680#step:6:172
- `posts` test pass when they are run alone
- when they are run after `playlist` tests, requests are rejected with `400` (badRequest) by `handleRequest` because `user` is an empty object. Hence the hypothesis of the test users not being properly …
> fix(tests): better isolation of API tests => remove FIXMEs

- app/infrastructure/ImageStorage.js
- app/models/mongodb.js
- app/nodejs-type-extensions.d.ts
- test/api-client.js
- test/api/auth.api.tests.js
- test/api/base.api.tests.js
- test/api/data.api.tests.js
- test/api/follow.api.tests.js
- test/api/legacy.post.api.tests.js
- test/api/playlist.api.tests.js
- test/api/post.api.tests.js
- test/api/security.api.tests.js
- test/api/user.api.tests.js
- test/approval-tests-helpers.js
- test/approval/hot-tracks/hot-tracks.approval.test.js
- test/approval/posting/posting.approval.tests.js
- test/approval/routes/routes.approval.tests.js
- test/fixtures.js
- test/integration/notif-tests.js
- test/integration/user.repository.tests.js
- test/reset-test-db.js
Fixes #684.
Follow up of PR #687.
Improvements:
- Make sure that db state is reset everywhere it needs to be, ideally before each test, to ensure state isolation and prevent side effects.
- Use `OpenwhydTestEnv.reset()` instead of `fixtures.cleanup()`, where applicable.
> fix(tests): improve test isolation and harmonize use of `OpenwhydTestEnv`

- .github/workflows/ci.yml
- .releaserc.js
- Makefile
Problem: `CHANGELOG.md` has not been updated by semantic-release for 2 years!
Add `@semantic-release/release-notes-generator` plugin, as suggested in https://www.npmjs.com/package/@semantic-release/changelog.
> fix(ci): update `CHANGELOG.md` on release

- app/controllers/admin/db.js
- app/controllers/admin/invites.js
- app/models/activity.js
- app/models/track.js
Similar to #703.
Incorrect error handling logic:
```js
search()
.catch(/* ... */) // error/`reject` handling code
.then(/* ... */) // success/`resolve` handling code
```
... causing both error and success handling code to run.
Fix promise handling so that callbacks are called only once: if promise resolves OR rejects, not both.
Will also possibly fix several `Can't set headers after they are sent` errors witnessed in production logs.
> fix(error-handling): don't callback twice upon rejection

- app/models/track.js
- test/unit/hot-tracks.tests.js
Contributes to #718 and #614.
The top track listed on the [hot tracks page](https://openwhyd.org/hot) has an invalid SoundCloud `eId`, causing its score to artificially accumulate the stats of all posts with that same invalid `eId: "/sc/undefined"`.
```json
{
"_id": "53f5d7af7b4e770b172679bc",
"uId": "52e2620f7e91c862b2b3f66a",
"uNm": "Rien",
"text": "",
"pl": { "name": "Balkan Beat Gypsy #03", "id": 144 },
"name": "Haris Pilton - Gypsy Partizans (2013)",
"eId": "/sc/undefined",
"img": "https://i1.sndcdn.com/artworks-000047093292-y6wbnv-large.jpg?e76cf77",
"nbP": 958,
"lov": [
"53da584ce04b7b4fca7cf528",
"518b5a447e91c862b2adea1a",
"6485e598d1b1033fa650d66b"
],
"nbR": 213,
"score": 900,
"nbL": 19,
"prev": 900,
"trackId": "54bf88e3e04b7b4fca82c18f",
"rankIncr": 0,
"trackUrl": …
```
> fix(hot-tracks): don't include invalid SoundCloud `eId`

- app/controllers/api/user.js
I want to receive fewer warnings like this one from Datadog:
> fix(logs): reduce error logs from fieldSetters

- app/models/mongodb.js
- app/models/user.js
- app/workers/notifEmails.js
Whenever a db error happens during the generation of a notification digest email, the `notifEmails` worker hangs, causing a loop of `[OneAtATime] fct is trying to start before last call has ended` errors.
The problem was probably revealed while migrating on #634, because of not calling "`cb`" callback functions in case of errors returned by `async` mongodb calls.
- Intercept errors, so the execution of the worker can end and be restarted later in case of unexpected interruption.
- => turn callback-based functions into `async` functions, so that errors can be intercepted.
> fix: end worker process in case of error

- .gitignore
- env-vars-testing.conf
- scripts/auth0/import-prod-get-error.sh
- scripts/auth0/import-prod-users.sh
- scripts/auth0/prepare-import-batches.js
- scripts/restart.sh
Follow up of #705. May contribute to #669.
Usage, from project root dir:
```sh
$ mongoexport -d ${dbname} -c user --type=json --out ./prod-users.json-lines -u ${dbuser} -p ${dbpassword}
$ node ./scripts/auth0/prepare-import-batches.js # => create files: `prod-users-*.for-auth0.json`
$ ./scripts/auth0/import-prod-users.sh
```
> fix(auth): add scripts to import users to auth0

- env-vars-testing-local.sh
- scripts/import-posts.js
Help Robert (and other users) import his playlists to his new account.
- the list of playlists of the destination user will be overwritten
=> existing tracks (if any) on that profile may end up in old playlists.
- on each imported track, the number of plays, reposts and likes will be reset to zero.
```sh
$ . ./env-vars-testing-local.sh
$ node scripts/import-from-prod.js adrien # imports 21 tracks from openwhyd.com/adrien --> local id: 4d94501d1f78ac091dbc9b4d
$ node scripts/import-posts.js 4d94501d1f78ac091dbc9b4d 000000000000000000000002 # copy to local id: 000000000000000000000002
```
```sh
$ . env-vars-local.sh
$ node scripts/import-posts.js 5f0f0d701125f9d3afca1bcc 6591c8dd0890c870388d2508 # imports all posts from https://openwhyd.org/u/5f0f0d701125f9d3afca1bcc
```
> chore: script to import user tracks to another user

- .github/workflows/ci.yml
- Makefile
- README.md
- docs/INSTALL.md
- docs/howto-deploy-on-digitalocean.md
cf https://github.com/openwhyd/openwhyd/actions/runs/10227189085/job/28298375126#step:3:8:
Call `docker compose` instead of legacy command: `docker-compose`.
> fix(ci): `docker-compose: command not found`

- .github/workflows/ci.yml
`cp: cannot stat 'coverage-cypress/.nyc_output/*.json': No such file or directory` error from https://github.com/openwhyd/openwhyd/actions/runs/11870400622/job/33082183227?pr=776#step:7:15
> ci: fix error when merging coverage reports

- misc/BrowserExt/Chrome/bookmarklet.js
- public/js/bookmarklet.js
- public/js/bookmarkletUrlDetectors.ts
cf https://sonarcloud.io/project/security_hotspots?id=openwhyd_openwhyd&branch=main&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true
> fix(bookmarklet): safer way to trim whitespace from titles 

- app/lib/auth0/features.js
- app/models/user.js
When a user tries to change their profile name to an empty string:
- Auth0 rejects
- the error is logged twice
- but the renaming happens in db anyway
- and no user feedback is provided.
Error logs:
```
07:26:09 UTC | openwhyd-2gb
[31m Error -- Tue, 24 Dec 2024 07:26:08 GMT Trace: failed to forward user rename to Auth0: ManagementApiError: Payload validation error: 'String is too short (0 chars), minimum 1' on property name (Name of this user).
07:26:08 UTC | openwhyd-2gb
msg: "Payload validation error: 'String is too short (0 chars), minimum 1' on property name (Name of this user)."
07:26:08 UTC | openwhyd-2gb
body: `{"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'String is too short (0 chars), minimum 1' on property name (Name of this …
```
> fix: don't allow user renaming in case of validation error

- app/controllers/private/register.js
- public/js/settings.js
When a user deletes their account, their session remains active whereas they were removes from the `usernames` cache => notification poll pollutes logs with `logged user <UID> not found in user cache` errors.
After deleting a user account, also logout.
> fix(users): logout after user deletion

- app/controllers/private/register.js
- app/lib/auth0/index.js
Follow up of https://github.com/openwhyd/openwhyd/commit/67e39b56ced420963d886952749a661139f22727.
As explained in [\`oidc.isAuthenticated()\` returns true even though the user does not exist in Auth0 - Auth0 Community](https://community.auth0.com/t/oidc-isauthenticated-returns-true-even-though-the-user-does-not-exist-in-auth0/169242/1): logs show that some users are logged in on openwhyd.org but don't have a user account on our db. This causes `logged user <UID> not found in user cache` warnings, and prevents the user to add tracks to their profile.
How to reproduce, as a visitor on openwhyd.org:
- click on login
- on the auth0 form, click on signup
- enter credentials for new user account
=> you are redirected to openwhyd.org, the login button is still visible (as if you were not logged …
> fix(auth): always check if logged in user needs to register/signup

- app/lib/my-http-wrapper/http/Application.js
follow up of PR #806.
```
$ node app/test-api-v2.js
response: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>InvalidTokenError: Unexpected &#39;aud&#39; value<br> &nbsp; &nbsp;at /home/adrien/openwhyd/node_modules/express-oauth2-jwt-bearer/dist/index.js:300:19<br> &nbsp; &nbsp;at async /home/adrien/openwhyd/node_modules/express-oauth2-jwt-bearer/dist/index.js:403:24</pre>
</body>
</html>
```
- update audience by using the right env var
- add TODO regarding format/rendering of auth errors, in response to API requests
> fix(api): `InvalidTokenError: Unexpected "aud" value`

- app/lib/my-http-wrapper/http/Application.js
Error spotted in production logs, after depoying https://github.com/openwhyd/openwhyd/pull/808 and posting a track to openwhyd.org/adrien from telegram bot:
```
0|openwhyd | ❌ Error -- Wed, 26 Mar 2025 13:14:39 GMT ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
0|openwhyd |     at Object.xForwardedForHeader (/home/adrien/openwhyd/node_modules/express-rate-limit/dist/index.cjs:187:13)
0|openwhyd |     at wrappedValidations.<computed> [as xForwardedForHeader] (/home/adrien/openwhyd/node_modules/express-rate-limit/dist/in …
```
> fix(api): make rate limiter work with HTTP proxy (cloudflare and/or nginx)

- .github/workflows/ci.yml
- app/models/notif.js
- test/api/post.api.tests.js
Error spotted several times in production logs:
```
[31m❌ Error -- Fri, 04 Apr 2025 21:23:32 GMT TypeError: Cannot read properties of null (reading 'lov')
at exports.unlove (/home/adrien/openwhyd/app/models/notif.js:270:12)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
```
This happens because the `unlove` function from `notif.js` is passed a whole `post` object (like for the `love` function), whereas that function expects a `pId` value instead.
=> Fix this error by harmonizing parameters for the `love` and `unlove` function: both should take a `post` object.
> fix(notif): uncaught error when unloving a post

- .github/workflows/ci.yml
- Makefile
CI checks don't run:
Because of a `This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101` error:
Update ubuntu version used in CI, as suggested in https://github.com/actions/runner-images/issues/11101.
CI checks pass.
> fix(ci): use more recent ubuntu version

- app/controllers/api/post.js
- app/controllers/api/user.js
Error found [on datadog](https://app.datadoghq.com/logs?query=host%3Aopenwhyd-2gb%20service%3Aopenwhyd&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZcbbucOAADOssONU5Z6PQBN&fromUser=true&link_source=monitor_notif&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=&from_ts=1748511641697&to_ts=1748511996763&live=false):
A `GET /api/post?action=lovers&...` request lead to logging a `BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer (value: undefined)` error, which are now appearing often in logs.
Instead of polluting logs, return an error to the caller of the API endpoint.
> fix(api): validate parameters of post api

- app/controllers/private/search.js
- app/templates/search.js
The search page does not respond:
https://github.com/user-attachments/assets/416255d3-559c-42cc-800b-4f457dedd832
- make the search respond by handling the case where there are no posts/tracks returned by Algolia
- include `posts` (instead of `tracks`)
> fix(search): make search controller respond with posts

- app/models/mongodb-shell-runner.js
- app/models/mongodb.js
- config/initdb.js
- test/integration/notif-tests.js
- test/reset-test-db.js
When restarting openwhyd in production, the db initialization step (which includes migrations) takes 10~20 seconds to run, which is significant.
Investigate which part of this initialization takes most time, so we can optimize it.
> fix(start-up): print steps of db initialization + use promises

- .github/workflows/ci.yml
- app/models/post.js
- scripts/import-from-prod.js
Closes #.
The stream of posts listed in the user's home feed ends prematurely when it contains at least one track that was reposted from a followed user.
https://github.com/user-attachments/assets/4696e183-74cf-4c6c-b3ee-1ccbd5d73bc4
This is probably a regression introduced when decommissioning the `forEach2` function, in https://github.com/openwhyd/openwhyd/pull/833.
- Fix main issue by giving control of the `limit` to our cursor-based iteration logic, instead of passing it to `find()`.
- Fix Cypress tests on CI by forcing the use of [browser-actions/setup-chrome@v1](https://github.com/browser-actions/setup-chrome/releases/tag/v1.7.3)
> fix(stream): home feed should not end prematurely + fix Cypress tests on CI

- app/models/notifEmails.js
Full error message found in production logs after a call to `/api/follow/action=insert`:
```
[EMAIL] send error: Error: The subject field is required #MS42209 (and 3 more errors)
```
- Await calls to async functions that generate email content.
> fix(email): `[EMAIL] send error: Error: The subject field is required

- app/controllers/api/user.js
The following error (happening when a user tries to set a handle value that is longer than allowed) was logged several times even though it's returned as a response to the request that causes is:
```
api.user.controller ERROR: Must be less than 18 characters long
```
- This is a user-facing error => don't log it
- Bonus: rename `localRendering` parameters to `callback`, to make the logic easier to understand
Tested manually by sending a too long handle value => the error message is displayed in the UI.
> fix(user-controller): don't log error about handle validation
